/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppointmentWithId = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'serviceName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'queueNumber' : IDL.Nat,
  'servicePrice' : IDL.Float64,
  'salonId' : IDL.Nat,
});
export const CustomerProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const PlanPricing = IDL.Record({
  'originalPrice' : IDL.Float64,
  'discountPercent' : IDL.Float64,
  'planDays' : IDL.Nat,
  'planName' : IDL.Text,
});
export const SalonWithId = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Opt(IDL.Float64),
  'trialDays' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'ownerPhone' : IDL.Text,
  'pendingApproval' : IDL.Bool,
  'isActive' : IDL.Bool,
  'subscriptionActive' : IDL.Bool,
  'longitude' : IDL.Opt(IDL.Float64),
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'trialStartDate' : IDL.Int,
  'closedDays' : IDL.Vec(IDL.Bool),
});
export const ServiceWithId = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'price' : IDL.Float64,
  'salonId' : IDL.Nat,
});
export const SubRequest = IDL.Record({
  'id' : IDL.Nat,
  'finalPrice' : IDL.Float64,
  'status' : IDL.Text,
  'originalPrice' : IDL.Float64,
  'approvedAt' : IDL.Int,
  'ownerPhone' : IDL.Text,
  'discountPercent' : IDL.Float64,
  'savings' : IDL.Float64,
  'planDays' : IDL.Nat,
  'screenshotBase64' : IDL.Text,
  'planName' : IDL.Text,
  'salonName' : IDL.Text,
  'requestTime' : IDL.Int,
});
export const DashboardStats = IDL.Record({
  'total' : IDL.Nat,
  'active' : IDL.Nat,
  'expired' : IDL.Nat,
  'pending' : IDL.Nat,
});
export const RevenueStats = IDL.Record({
  'perSalon' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Float64)),
  'totalRevenue' : IDL.Float64,
  'monthlyRevenue' : IDL.Float64,
});
export const SubscriptionHistory = IDL.Record({
  'id' : IDL.Nat,
  'finalPrice' : IDL.Float64,
  'originalPrice' : IDL.Float64,
  'endDate' : IDL.Int,
  'approvedAt' : IDL.Int,
  'ownerPhone' : IDL.Text,
  'discountPercent' : IDL.Float64,
  'savings' : IDL.Float64,
  'planDays' : IDL.Nat,
  'planName' : IDL.Text,
  'salonName' : IDL.Text,
  'salonId' : IDL.Nat,
  'transactionId' : IDL.Text,
  'startDate' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceSession = IDL.Record({
  'startTime' : IDL.Int,
  'durationMinutes' : IDL.Nat,
  'appointmentId' : IDL.Nat,
});
export const OwnerRevenueSummary = IDL.Record({
  'monthlyEarnings' : IDL.Float64,
  'completedAppointments' : IDL.Nat,
  'totalEarnings' : IDL.Float64,
  'totalAppointments' : IDL.Nat,
});
export const PushSubscription = IDL.Record({
  'endpoint' : IDL.Text,
  'auth' : IDL.Text,
  'p256dh' : IDL.Text,
});
export const QueueScheduleEntry = IDL.Record({
  'customerName' : IDL.Text,
  'serviceName' : IDL.Text,
  'estimatedStartTime' : IDL.Int,
  'queueNumber' : IDL.Nat,
  'appointmentId' : IDL.Nat,
});
export const SalonPhoto = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'ownerPhone' : IDL.Text,
  'salonId' : IDL.Nat,
  'uploadedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addSalonServiceByPhone' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Float64, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'adminApproveSalon' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'adminApproveSubRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'adminExpireOldSubRequests' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'adminGetAllAppointmentsForBackup' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(AppointmentWithId)],
      ['query'],
    ),
  'adminGetAllCustomersForBackup' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(CustomerProfile)],
      ['query'],
    ),
  'adminGetAllPlanPricings' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(PlanPricing)],
      ['query'],
    ),
  'adminGetAllSalons' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(SalonWithId)],
      ['query'],
    ),
  'adminGetAllSalonsForBackup' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(SalonWithId)],
      ['query'],
    ),
  'adminGetAllServicesForBackup' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ServiceWithId)],
      ['query'],
    ),
  'adminGetAllSubRequests' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(SubRequest)],
      ['query'],
    ),
  'adminGetDashboardStats' : IDL.Func(
      [IDL.Text, IDL.Text],
      [DashboardStats],
      ['query'],
    ),
  'adminGetDefaultTrialDays' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Nat],
      ['query'],
    ),
  'adminGetNextIdsForBackup' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Nat, IDL.Nat, IDL.Nat],
      ['query'],
    ),
  'adminGetOwnerPhoneMapForBackup' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'adminGetPendingSalons' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(SalonWithId)],
      ['query'],
    ),
  'adminGetPendingSubRequests' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(SubRequest)],
      ['query'],
    ),
  'adminGetRevenueStats' : IDL.Func(
      [IDL.Text, IDL.Text],
      [RevenueStats],
      ['query'],
    ),
  'adminGetSubHistory' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(SubscriptionHistory)],
      ['query'],
    ),
  'adminGetSubRequestEarnings' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Float64, IDL.Float64, IDL.Nat],
      ['query'],
    ),
  'adminGetSubscriptionPrice' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Float64],
      ['query'],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'adminPasswordIsSet' : IDL.Func([], [IDL.Bool], ['query']),
  'adminProcessTrialExpirations' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'adminRejectSalon' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'adminRejectSubRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'adminResetOwnerPassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'adminRestoreAllData' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(SalonWithId),
        IDL.Vec(ServiceWithId),
        IDL.Vec(AppointmentWithId),
        IDL.Vec(CustomerProfile),
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'adminSetDefaultTrialDays' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'adminSetPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'adminSetPlanPricing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'adminSetSalonActive' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'adminSetSalonSubscription' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'adminSetSalonTrialDays' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'adminSetSubscriptionPrice' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointmentByPhone' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'clearServiceSession' : IDL.Func([IDL.Text], [], []),
  'deleteSalonPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deleteSalonServiceByPhone' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'getAllActiveSalons' : IDL.Func([], [IDL.Vec(SalonWithId)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentServiceSession' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ServiceSession)],
      ['query'],
    ),
  'getMyAppointmentsByPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AppointmentWithId)],
      ['query'],
    ),
  'getMyCustomerProfileByPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CustomerProfile)],
      ['query'],
    ),
  'getMySubHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SubscriptionHistory)],
      ['query'],
    ),
  'getMySubRequests' : IDL.Func([IDL.Text], [IDL.Vec(SubRequest)], ['query']),
  'getOwnerRevenueSummaryByPhone' : IDL.Func(
      [IDL.Text],
      [OwnerRevenueSummary],
      ['query'],
    ),
  'getOwnerSalonByPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SalonWithId)],
      ['query'],
    ),
  'getPendingNotifications' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'getPlanPricings' : IDL.Func([], [IDL.Vec(PlanPricing)], ['query']),
  'getPushSubscription' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(PushSubscription)],
      ['query'],
    ),
  'getQueueInfo' : IDL.Func([IDL.Nat], [IDL.Nat, IDL.Nat], ['query']),
  'getQueueScheduleForSalon' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(QueueScheduleEntry)],
      ['query'],
    ),
  'getSalonAppointmentsForDateByPhone' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Vec(AppointmentWithId)],
      ['query'],
    ),
  'getSalonById' : IDL.Func([IDL.Nat], [IDL.Opt(SalonWithId)], ['query']),
  'getSalonClosedDays' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(IDL.Bool), 'err' : IDL.Text })],
      ['query'],
    ),
  'getSalonPhotos' : IDL.Func([IDL.Nat], [IDL.Vec(SalonPhoto)], ['query']),
  'getSalonServices' : IDL.Func([IDL.Nat], [IDL.Vec(ServiceWithId)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationSent' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'registerSalonByPhone' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'salonOwnerLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Text, IDL.Opt(SalonWithId)],
      ['query'],
    ),
  'salonOwnerRegisterV2' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [IDL.Text],
      [],
    ),
  'salonOwnerSetPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'saveCustomerProfileByPhone' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'savePushSubscription' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'setSalonClosedDays' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Bool)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'startServiceSession' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'submitSubscriptionRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'updateAppointmentStatusByPhone' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateOwnerSalonByPhone' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateSalonLocation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Bool],
      [],
    ),
  'uploadSalonPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppointmentWithId = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'serviceName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'queueNumber' : IDL.Nat,
    'servicePrice' : IDL.Float64,
    'salonId' : IDL.Nat,
  });
  const CustomerProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const PlanPricing = IDL.Record({
    'originalPrice' : IDL.Float64,
    'discountPercent' : IDL.Float64,
    'planDays' : IDL.Nat,
    'planName' : IDL.Text,
  });
  const SalonWithId = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Opt(IDL.Float64),
    'trialDays' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'ownerPhone' : IDL.Text,
    'pendingApproval' : IDL.Bool,
    'isActive' : IDL.Bool,
    'subscriptionActive' : IDL.Bool,
    'longitude' : IDL.Opt(IDL.Float64),
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'trialStartDate' : IDL.Int,
    'closedDays' : IDL.Vec(IDL.Bool),
  });
  const ServiceWithId = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'price' : IDL.Float64,
    'salonId' : IDL.Nat,
  });
  const SubRequest = IDL.Record({
    'id' : IDL.Nat,
    'finalPrice' : IDL.Float64,
    'status' : IDL.Text,
    'originalPrice' : IDL.Float64,
    'approvedAt' : IDL.Int,
    'ownerPhone' : IDL.Text,
    'discountPercent' : IDL.Float64,
    'savings' : IDL.Float64,
    'planDays' : IDL.Nat,
    'screenshotBase64' : IDL.Text,
    'planName' : IDL.Text,
    'salonName' : IDL.Text,
    'requestTime' : IDL.Int,
  });
  const DashboardStats = IDL.Record({
    'total' : IDL.Nat,
    'active' : IDL.Nat,
    'expired' : IDL.Nat,
    'pending' : IDL.Nat,
  });
  const RevenueStats = IDL.Record({
    'perSalon' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Float64)),
    'totalRevenue' : IDL.Float64,
    'monthlyRevenue' : IDL.Float64,
  });
  const SubscriptionHistory = IDL.Record({
    'id' : IDL.Nat,
    'finalPrice' : IDL.Float64,
    'originalPrice' : IDL.Float64,
    'endDate' : IDL.Int,
    'approvedAt' : IDL.Int,
    'ownerPhone' : IDL.Text,
    'discountPercent' : IDL.Float64,
    'savings' : IDL.Float64,
    'planDays' : IDL.Nat,
    'planName' : IDL.Text,
    'salonName' : IDL.Text,
    'salonId' : IDL.Nat,
    'transactionId' : IDL.Text,
    'startDate' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceSession = IDL.Record({
    'startTime' : IDL.Int,
    'durationMinutes' : IDL.Nat,
    'appointmentId' : IDL.Nat,
  });
  const OwnerRevenueSummary = IDL.Record({
    'monthlyEarnings' : IDL.Float64,
    'completedAppointments' : IDL.Nat,
    'totalEarnings' : IDL.Float64,
    'totalAppointments' : IDL.Nat,
  });
  const PushSubscription = IDL.Record({
    'endpoint' : IDL.Text,
    'auth' : IDL.Text,
    'p256dh' : IDL.Text,
  });
  const QueueScheduleEntry = IDL.Record({
    'customerName' : IDL.Text,
    'serviceName' : IDL.Text,
    'estimatedStartTime' : IDL.Int,
    'queueNumber' : IDL.Nat,
    'appointmentId' : IDL.Nat,
  });
  const SalonPhoto = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'ownerPhone' : IDL.Text,
    'salonId' : IDL.Nat,
    'uploadedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addSalonServiceByPhone' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Float64, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'adminApproveSalon' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'adminApproveSubRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'adminExpireOldSubRequests' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'adminGetAllAppointmentsForBackup' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(AppointmentWithId)],
        ['query'],
      ),
    'adminGetAllCustomersForBackup' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(CustomerProfile)],
        ['query'],
      ),
    'adminGetAllPlanPricings' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(PlanPricing)],
        ['query'],
      ),
    'adminGetAllSalons' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(SalonWithId)],
        ['query'],
      ),
    'adminGetAllSalonsForBackup' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(SalonWithId)],
        ['query'],
      ),
    'adminGetAllServicesForBackup' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ServiceWithId)],
        ['query'],
      ),
    'adminGetAllSubRequests' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(SubRequest)],
        ['query'],
      ),
    'adminGetDashboardStats' : IDL.Func(
        [IDL.Text, IDL.Text],
        [DashboardStats],
        ['query'],
      ),
    'adminGetDefaultTrialDays' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Nat],
        ['query'],
      ),
    'adminGetNextIdsForBackup' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Nat, IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'adminGetOwnerPhoneMapForBackup' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'adminGetPendingSalons' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(SalonWithId)],
        ['query'],
      ),
    'adminGetPendingSubRequests' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(SubRequest)],
        ['query'],
      ),
    'adminGetRevenueStats' : IDL.Func(
        [IDL.Text, IDL.Text],
        [RevenueStats],
        ['query'],
      ),
    'adminGetSubHistory' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(SubscriptionHistory)],
        ['query'],
      ),
    'adminGetSubRequestEarnings' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Float64, IDL.Float64, IDL.Nat],
        ['query'],
      ),
    'adminGetSubscriptionPrice' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Float64],
        ['query'],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'adminPasswordIsSet' : IDL.Func([], [IDL.Bool], ['query']),
    'adminProcessTrialExpirations' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'adminRejectSalon' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'adminRejectSubRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'adminResetOwnerPassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'adminRestoreAllData' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(SalonWithId),
          IDL.Vec(ServiceWithId),
          IDL.Vec(AppointmentWithId),
          IDL.Vec(CustomerProfile),
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'adminSetDefaultTrialDays' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'adminSetPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'adminSetPlanPricing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'adminSetSalonActive' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'adminSetSalonSubscription' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'adminSetSalonTrialDays' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'adminSetSubscriptionPrice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointmentByPhone' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'clearServiceSession' : IDL.Func([IDL.Text], [], []),
    'deleteSalonPhoto' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'deleteSalonServiceByPhone' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'getAllActiveSalons' : IDL.Func([], [IDL.Vec(SalonWithId)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentServiceSession' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ServiceSession)],
        ['query'],
      ),
    'getMyAppointmentsByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AppointmentWithId)],
        ['query'],
      ),
    'getMyCustomerProfileByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'getMySubHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SubscriptionHistory)],
        ['query'],
      ),
    'getMySubRequests' : IDL.Func([IDL.Text], [IDL.Vec(SubRequest)], ['query']),
    'getOwnerRevenueSummaryByPhone' : IDL.Func(
        [IDL.Text],
        [OwnerRevenueSummary],
        ['query'],
      ),
    'getOwnerSalonByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SalonWithId)],
        ['query'],
      ),
    'getPendingNotifications' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'getPlanPricings' : IDL.Func([], [IDL.Vec(PlanPricing)], ['query']),
    'getPushSubscription' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(PushSubscription)],
        ['query'],
      ),
    'getQueueInfo' : IDL.Func([IDL.Nat], [IDL.Nat, IDL.Nat], ['query']),
    'getQueueScheduleForSalon' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(QueueScheduleEntry)],
        ['query'],
      ),
    'getSalonAppointmentsForDateByPhone' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Vec(AppointmentWithId)],
        ['query'],
      ),
    'getSalonById' : IDL.Func([IDL.Nat], [IDL.Opt(SalonWithId)], ['query']),
    'getSalonClosedDays' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(IDL.Bool), 'err' : IDL.Text })],
        ['query'],
      ),
    'getSalonPhotos' : IDL.Func([IDL.Nat], [IDL.Vec(SalonPhoto)], ['query']),
    'getSalonServices' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ServiceWithId)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationSent' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'registerSalonByPhone' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'salonOwnerLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text, IDL.Opt(SalonWithId)],
        ['query'],
      ),
    'salonOwnerRegisterV2' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [IDL.Text],
        [],
      ),
    'salonOwnerSetPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'saveCustomerProfileByPhone' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'savePushSubscription' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'setSalonClosedDays' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Bool)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'startServiceSession' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'submitSubscriptionRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'updateAppointmentStatusByPhone' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateOwnerSalonByPhone' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateSalonLocation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Bool],
        [],
      ),
    'uploadSalonPhoto' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };