/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SalonWithId = IDL.Record({
  'id' : IDL.Nat,
  'trialDays' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'ownerPhone' : IDL.Text,
  'pendingApproval' : IDL.Bool,
  'isActive' : IDL.Bool,
  'subscriptionActive' : IDL.Bool,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'trialStartDate' : IDL.Int,
});
export const DashboardStats = IDL.Record({
  'total' : IDL.Nat,
  'active' : IDL.Nat,
  'expired' : IDL.Nat,
  'pending' : IDL.Nat,
});
export const RevenueStats = IDL.Record({
  'perSalon' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Float64)),
  'totalRevenue' : IDL.Float64,
  'monthlyRevenue' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppointmentWithId = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'serviceName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'queueNumber' : IDL.Nat,
  'servicePrice' : IDL.Float64,
  'salonId' : IDL.Nat,
});
export const CustomerProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const OwnerRevenueSummary = IDL.Record({
  'monthlyEarnings' : IDL.Float64,
  'completedAppointments' : IDL.Nat,
  'totalEarnings' : IDL.Float64,
  'totalAppointments' : IDL.Nat,
});
export const ServiceWithId = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'price' : IDL.Float64,
  'salonId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSalonServiceByPhone' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Float64, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'adminApproveSalon' : IDL.Func([IDL.Nat], [], []),
  'adminGetAllSalons' : IDL.Func([], [IDL.Vec(SalonWithId)], ['query']),
  'adminGetDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'adminGetDefaultTrialDays' : IDL.Func([], [IDL.Nat], ['query']),
  'adminGetPendingSalons' : IDL.Func([], [IDL.Vec(SalonWithId)], ['query']),
  'adminGetRevenueStats' : IDL.Func([], [RevenueStats], ['query']),
  'adminGetSubscriptionPrice' : IDL.Func([], [IDL.Float64], ['query']),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'adminPasswordIsSet' : IDL.Func([], [IDL.Bool], ['query']),
  'adminProcessTrialExpirations' : IDL.Func([], [IDL.Nat], []),
  'adminRejectSalon' : IDL.Func([IDL.Nat], [], []),
  'adminSetDefaultTrialDays' : IDL.Func([IDL.Nat], [], []),
  'adminSetPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'adminSetSalonActive' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'adminSetSalonSubscription' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'adminSetSalonTrialDays' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'adminSetSubscriptionPrice' : IDL.Func([IDL.Float64], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointmentByPhone' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteSalonServiceByPhone' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'getAllActiveSalons' : IDL.Func([], [IDL.Vec(SalonWithId)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyAppointmentsByPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AppointmentWithId)],
      ['query'],
    ),
  'getMyCustomerProfileByPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CustomerProfile)],
      ['query'],
    ),
  'getOwnerRevenueSummaryByPhone' : IDL.Func(
      [IDL.Text],
      [OwnerRevenueSummary],
      ['query'],
    ),
  'getOwnerSalonByPhone' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SalonWithId)],
      ['query'],
    ),
  'getQueueInfo' : IDL.Func([IDL.Nat], [IDL.Nat, IDL.Nat], ['query']),
  'getSalonAppointmentsForDateByPhone' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Vec(AppointmentWithId)],
      ['query'],
    ),
  'getSalonById' : IDL.Func([IDL.Nat], [IDL.Opt(SalonWithId)], ['query']),
  'getSalonServices' : IDL.Func([IDL.Nat], [IDL.Vec(ServiceWithId)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerSalonByPhone' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCustomerProfileByPhone' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateAppointmentStatusByPhone' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateOwnerSalonByPhone' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SalonWithId = IDL.Record({
    'id' : IDL.Nat,
    'trialDays' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'ownerPhone' : IDL.Text,
    'pendingApproval' : IDL.Bool,
    'isActive' : IDL.Bool,
    'subscriptionActive' : IDL.Bool,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'trialStartDate' : IDL.Int,
  });
  const DashboardStats = IDL.Record({
    'total' : IDL.Nat,
    'active' : IDL.Nat,
    'expired' : IDL.Nat,
    'pending' : IDL.Nat,
  });
  const RevenueStats = IDL.Record({
    'perSalon' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Float64)),
    'totalRevenue' : IDL.Float64,
    'monthlyRevenue' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppointmentWithId = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'serviceName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'queueNumber' : IDL.Nat,
    'servicePrice' : IDL.Float64,
    'salonId' : IDL.Nat,
  });
  const CustomerProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const OwnerRevenueSummary = IDL.Record({
    'monthlyEarnings' : IDL.Float64,
    'completedAppointments' : IDL.Nat,
    'totalEarnings' : IDL.Float64,
    'totalAppointments' : IDL.Nat,
  });
  const ServiceWithId = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'price' : IDL.Float64,
    'salonId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSalonServiceByPhone' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Float64, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'adminApproveSalon' : IDL.Func([IDL.Nat], [], []),
    'adminGetAllSalons' : IDL.Func([], [IDL.Vec(SalonWithId)], ['query']),
    'adminGetDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'adminGetDefaultTrialDays' : IDL.Func([], [IDL.Nat], ['query']),
    'adminGetPendingSalons' : IDL.Func([], [IDL.Vec(SalonWithId)], ['query']),
    'adminGetRevenueStats' : IDL.Func([], [RevenueStats], ['query']),
    'adminGetSubscriptionPrice' : IDL.Func([], [IDL.Float64], ['query']),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'adminPasswordIsSet' : IDL.Func([], [IDL.Bool], ['query']),
    'adminProcessTrialExpirations' : IDL.Func([], [IDL.Nat], []),
    'adminRejectSalon' : IDL.Func([IDL.Nat], [], []),
    'adminSetDefaultTrialDays' : IDL.Func([IDL.Nat], [], []),
    'adminSetPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'adminSetSalonActive' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'adminSetSalonSubscription' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'adminSetSalonTrialDays' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'adminSetSubscriptionPrice' : IDL.Func([IDL.Float64], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointmentByPhone' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteSalonServiceByPhone' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'getAllActiveSalons' : IDL.Func([], [IDL.Vec(SalonWithId)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyAppointmentsByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AppointmentWithId)],
        ['query'],
      ),
    'getMyCustomerProfileByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'getOwnerRevenueSummaryByPhone' : IDL.Func(
        [IDL.Text],
        [OwnerRevenueSummary],
        ['query'],
      ),
    'getOwnerSalonByPhone' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SalonWithId)],
        ['query'],
      ),
    'getQueueInfo' : IDL.Func([IDL.Nat], [IDL.Nat, IDL.Nat], ['query']),
    'getSalonAppointmentsForDateByPhone' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Vec(AppointmentWithId)],
        ['query'],
      ),
    'getSalonById' : IDL.Func([IDL.Nat], [IDL.Opt(SalonWithId)], ['query']),
    'getSalonServices' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ServiceWithId)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerSalonByPhone' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCustomerProfileByPhone' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateAppointmentStatusByPhone' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateOwnerSalonByPhone' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };