/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppointmentWithId {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'serviceName' : string,
  'customerPhone' : string,
  'date' : string,
  'createdAt' : bigint,
  'queueNumber' : bigint,
  'servicePrice' : number,
  'salonId' : bigint,
}
export interface CustomerProfile { 'name' : string, 'phone' : string }
export interface DashboardStats {
  'total' : bigint,
  'active' : bigint,
  'expired' : bigint,
  'pending' : bigint,
}
export interface OwnerRevenueSummary {
  'monthlyEarnings' : number,
  'completedAppointments' : bigint,
  'totalEarnings' : number,
  'totalAppointments' : bigint,
}
export interface PlanPricing {
  'originalPrice' : number,
  'discountPercent' : number,
  'planDays' : bigint,
  'planName' : string,
}
export interface PushSubscription {
  'endpoint' : string,
  'auth' : string,
  'p256dh' : string,
}
export interface QueueScheduleEntry {
  'customerName' : string,
  'serviceName' : string,
  'estimatedStartTime' : bigint,
  'queueNumber' : bigint,
  'appointmentId' : bigint,
}
export interface RevenueStats {
  'perSalon' : Array<[bigint, string, number]>,
  'totalRevenue' : number,
  'monthlyRevenue' : number,
}
export interface SalonPhoto {
  'id' : bigint,
  'url' : string,
  'ownerPhone' : string,
  'salonId' : bigint,
  'uploadedAt' : bigint,
}
export interface SalonWithId {
  'id' : bigint,
  'latitude' : [] | [number],
  'trialDays' : bigint,
  'city' : string,
  'name' : string,
  'ownerPhone' : string,
  'pendingApproval' : boolean,
  'isActive' : boolean,
  'subscriptionActive' : boolean,
  'longitude' : [] | [number],
  'address' : string,
  'phone' : string,
  'trialStartDate' : bigint,
}
export interface ServiceSession {
  'startTime' : bigint,
  'durationMinutes' : bigint,
  'appointmentId' : bigint,
}
export interface ServiceWithId {
  'id' : bigint,
  'name' : string,
  'durationMinutes' : bigint,
  'price' : number,
  'salonId' : bigint,
}
export interface SubRequest {
  'id' : bigint,
  'finalPrice' : number,
  'status' : string,
  'originalPrice' : number,
  'approvedAt' : bigint,
  'ownerPhone' : string,
  'discountPercent' : number,
  'savings' : number,
  'planDays' : bigint,
  'screenshotBase64' : string,
  'planName' : string,
  'salonName' : string,
  'requestTime' : bigint,
}
export interface SubscriptionHistory {
  'id' : bigint,
  'finalPrice' : number,
  'originalPrice' : number,
  'endDate' : bigint,
  'approvedAt' : bigint,
  'ownerPhone' : string,
  'discountPercent' : number,
  'savings' : number,
  'planDays' : bigint,
  'planName' : string,
  'salonName' : string,
  'salonId' : bigint,
  'transactionId' : string,
  'startDate' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addSalonServiceByPhone' : ActorMethod<
    [string, bigint, string, number, bigint],
    bigint
  >,
  'adminApproveSalon' : ActorMethod<[string, string, bigint], undefined>,
  'adminApproveSubRequest' : ActorMethod<[string, string, bigint], boolean>,
  'adminExpireOldSubRequests' : ActorMethod<[string, string], bigint>,
  'adminGetAllAppointmentsForBackup' : ActorMethod<
    [string, string],
    Array<AppointmentWithId>
  >,
  'adminGetAllCustomersForBackup' : ActorMethod<
    [string, string],
    Array<CustomerProfile>
  >,
  'adminGetAllPlanPricings' : ActorMethod<[string, string], Array<PlanPricing>>,
  'adminGetAllSalons' : ActorMethod<[string, string], Array<SalonWithId>>,
  'adminGetAllSalonsForBackup' : ActorMethod<
    [string, string],
    Array<SalonWithId>
  >,
  'adminGetAllServicesForBackup' : ActorMethod<
    [string, string],
    Array<ServiceWithId>
  >,
  'adminGetAllSubRequests' : ActorMethod<[string, string], Array<SubRequest>>,
  'adminGetDashboardStats' : ActorMethod<[string, string], DashboardStats>,
  'adminGetDefaultTrialDays' : ActorMethod<[string, string], bigint>,
  'adminGetNextIdsForBackup' : ActorMethod<
    [string, string],
    [bigint, bigint, bigint]
  >,
  'adminGetOwnerPhoneMapForBackup' : ActorMethod<
    [string, string],
    Array<[string, bigint]>
  >,
  'adminGetPendingSalons' : ActorMethod<[string, string], Array<SalonWithId>>,
  'adminGetPendingSubRequests' : ActorMethod<
    [string, string],
    Array<SubRequest>
  >,
  'adminGetRevenueStats' : ActorMethod<[string, string], RevenueStats>,
  'adminGetSubHistory' : ActorMethod<
    [string, string],
    Array<SubscriptionHistory>
  >,
  'adminGetSubRequestEarnings' : ActorMethod<
    [string, string],
    [number, number, bigint]
  >,
  'adminGetSubscriptionPrice' : ActorMethod<[string, string], number>,
  'adminLogin' : ActorMethod<[string, string], boolean>,
  'adminPasswordIsSet' : ActorMethod<[], boolean>,
  'adminProcessTrialExpirations' : ActorMethod<[string, string], bigint>,
  'adminRejectSalon' : ActorMethod<[string, string, bigint], undefined>,
  'adminRejectSubRequest' : ActorMethod<[string, string, bigint], boolean>,
  'adminResetOwnerPassword' : ActorMethod<
    [string, string, string, string],
    boolean
  >,
  'adminRestoreAllData' : ActorMethod<
    [
      string,
      string,
      Array<SalonWithId>,
      Array<ServiceWithId>,
      Array<AppointmentWithId>,
      Array<CustomerProfile>,
      Array<[string, bigint]>,
      bigint,
      bigint,
      bigint,
    ],
    undefined
  >,
  'adminSetDefaultTrialDays' : ActorMethod<[string, string, bigint], undefined>,
  'adminSetPassword' : ActorMethod<[string, string], boolean>,
  'adminSetPlanPricing' : ActorMethod<
    [string, string, string, number, number],
    undefined
  >,
  'adminSetSalonActive' : ActorMethod<
    [string, string, bigint, boolean],
    undefined
  >,
  'adminSetSalonSubscription' : ActorMethod<
    [string, string, bigint, boolean],
    undefined
  >,
  'adminSetSalonTrialDays' : ActorMethod<
    [string, string, bigint, bigint],
    undefined
  >,
  'adminSetSubscriptionPrice' : ActorMethod<
    [string, string, number],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointmentByPhone' : ActorMethod<
    [string, bigint, string, string, string],
    bigint
  >,
  'clearServiceSession' : ActorMethod<[string], undefined>,
  'deleteSalonPhoto' : ActorMethod<[string, string, bigint], boolean>,
  'deleteSalonServiceByPhone' : ActorMethod<
    [string, bigint, bigint],
    undefined
  >,
  'getAllActiveSalons' : ActorMethod<[], Array<SalonWithId>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentServiceSession' : ActorMethod<[bigint], [] | [ServiceSession]>,
  'getMyAppointmentsByPhone' : ActorMethod<[string], Array<AppointmentWithId>>,
  'getMyCustomerProfileByPhone' : ActorMethod<[string], [] | [CustomerProfile]>,
  'getMySubHistory' : ActorMethod<[string], Array<SubscriptionHistory>>,
  'getMySubRequests' : ActorMethod<[string], Array<SubRequest>>,
  'getOwnerRevenueSummaryByPhone' : ActorMethod<[string], OwnerRevenueSummary>,
  'getOwnerSalonByPhone' : ActorMethod<[string], [] | [SalonWithId]>,
  'getPendingNotifications' : ActorMethod<[bigint, string], Array<bigint>>,
  'getPlanPricings' : ActorMethod<[], Array<PlanPricing>>,
  'getPushSubscription' : ActorMethod<
    [string, string],
    [] | [PushSubscription]
  >,
  'getQueueInfo' : ActorMethod<[bigint], [bigint, bigint]>,
  'getQueueScheduleForSalon' : ActorMethod<
    [bigint, string],
    Array<QueueScheduleEntry>
  >,
  'getSalonAppointmentsForDateByPhone' : ActorMethod<
    [string, bigint, string],
    Array<AppointmentWithId>
  >,
  'getSalonById' : ActorMethod<[bigint], [] | [SalonWithId]>,
  'getSalonPhotos' : ActorMethod<[bigint], Array<SalonPhoto>>,
  'getSalonServices' : ActorMethod<[bigint], Array<ServiceWithId>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationSent' : ActorMethod<[string, bigint], undefined>,
  'registerSalonByPhone' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'salonOwnerLogin' : ActorMethod<
    [string, string],
    [string, [] | [SalonWithId]]
  >,
  'salonOwnerRegisterV2' : ActorMethod<
    [string, string, Array<string>, string],
    string
  >,
  'salonOwnerSetPassword' : ActorMethod<[string, string], boolean>,
  'saveCustomerProfileByPhone' : ActorMethod<[string, string], undefined>,
  'savePushSubscription' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'startServiceSession' : ActorMethod<[string, bigint, bigint], undefined>,
  'submitSubscriptionRequest' : ActorMethod<
    [string, string, string, bigint, number, number, number, number, string],
    bigint
  >,
  'updateAppointmentStatusByPhone' : ActorMethod<
    [string, bigint, string],
    undefined
  >,
  'updateOwnerSalonByPhone' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updateSalonLocation' : ActorMethod<
    [string, string, number, number],
    boolean
  >,
  'uploadSalonPhoto' : ActorMethod<[string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];