/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppointmentWithId {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'serviceName' : string,
  'customerPhone' : string,
  'date' : string,
  'createdAt' : bigint,
  'queueNumber' : bigint,
  'servicePrice' : number,
  'salonId' : bigint,
}
export interface CustomerProfile { 'name' : string, 'phone' : string }
export interface DashboardStats {
  'total' : bigint,
  'active' : bigint,
  'expired' : bigint,
  'pending' : bigint,
}
export interface OwnerRevenueSummary {
  'monthlyEarnings' : number,
  'completedAppointments' : bigint,
  'totalEarnings' : number,
  'totalAppointments' : bigint,
}
export interface RevenueStats {
  'perSalon' : Array<[bigint, string, number]>,
  'totalRevenue' : number,
  'monthlyRevenue' : number,
}
export interface SalonWithId {
  'id' : bigint,
  'trialDays' : bigint,
  'city' : string,
  'name' : string,
  'ownerPhone' : string,
  'pendingApproval' : boolean,
  'isActive' : boolean,
  'subscriptionActive' : boolean,
  'address' : string,
  'phone' : string,
  'trialStartDate' : bigint,
}
export interface ServiceWithId {
  'id' : bigint,
  'name' : string,
  'durationMinutes' : bigint,
  'price' : number,
  'salonId' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSalonServiceByPhone' : ActorMethod<
    [string, bigint, string, number, bigint],
    bigint
  >,
  'adminApproveSalon' : ActorMethod<[bigint], undefined>,
  'adminGetAllSalons' : ActorMethod<[], Array<SalonWithId>>,
  'adminGetDashboardStats' : ActorMethod<[], DashboardStats>,
  'adminGetDefaultTrialDays' : ActorMethod<[], bigint>,
  'adminGetPendingSalons' : ActorMethod<[], Array<SalonWithId>>,
  'adminGetRevenueStats' : ActorMethod<[], RevenueStats>,
  'adminGetSubscriptionPrice' : ActorMethod<[], number>,
  'adminLogin' : ActorMethod<[string, string], boolean>,
  'adminPasswordIsSet' : ActorMethod<[], boolean>,
  'adminResetOwnerPassword' : ActorMethod<[string, string], boolean>,
  'adminProcessTrialExpirations' : ActorMethod<[], bigint>,
  'adminRejectSalon' : ActorMethod<[bigint], undefined>,
  'adminSetDefaultTrialDays' : ActorMethod<[bigint], undefined>,
  'adminSetPassword' : ActorMethod<[string, string], boolean>,
  'adminSetSalonActive' : ActorMethod<[bigint, boolean], undefined>,
  'adminSetSalonSubscription' : ActorMethod<[bigint, boolean], undefined>,
  'adminSetSalonTrialDays' : ActorMethod<[bigint, bigint], undefined>,
  'adminSetSubscriptionPrice' : ActorMethod<[number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointmentByPhone' : ActorMethod<
    [string, bigint, string, string, string],
    bigint
  >,
  'deleteSalonServiceByPhone' : ActorMethod<
    [string, bigint, bigint],
    undefined
  >,
  'getAllActiveSalons' : ActorMethod<[], Array<SalonWithId>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAppointmentsByPhone' : ActorMethod<[string], Array<AppointmentWithId>>,
  'getMyCustomerProfileByPhone' : ActorMethod<[string], [] | [CustomerProfile]>,
  'getOwnerRevenueSummaryByPhone' : ActorMethod<[string], OwnerRevenueSummary>,
  'getOwnerSalonByPhone' : ActorMethod<[string], [] | [SalonWithId]>,
  'getQueueInfo' : ActorMethod<[bigint], [bigint, bigint]>,
  'getSalonAppointmentsForDateByPhone' : ActorMethod<
    [string, bigint, string],
    Array<AppointmentWithId>
  >,
  'getSalonById' : ActorMethod<[bigint], [] | [SalonWithId]>,
  'getSalonServices' : ActorMethod<[bigint], Array<ServiceWithId>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerSalonByPhone' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'salonOwnerLogin' : ActorMethod<[string, string], [string, [] | [SalonWithId]]>,
  'salonOwnerRegisterV2' : ActorMethod<[string, string, Array<string>, string], string>,
  'salonOwnerSetPassword' : ActorMethod<[string, string], boolean>,
  'saveCustomerProfileByPhone' : ActorMethod<[string, string], undefined>,
  'updateAppointmentStatusByPhone' : ActorMethod<
    [string, bigint, string],
    undefined
  >,
  'updateOwnerSalonByPhone' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];