/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Staff {
    name: string;
    role: string;
    email: string;
    specialty: string;
    phone: string;
}
export interface Service {
    duration: bigint;
    name: string;
    description?: string;
    price: number;
}
export interface Appointment {
    customerName: string;
    status: AppointmentStatus;
    serviceName: string;
    staffName: string;
    date: string;
    time: string;
    notes?: string;
    price: number;
}
export interface Customer {
    name: string;
    email: string;
    notes?: string;
    phone: string;
}
export interface DashboardStats {
    totalServices: bigint;
    totalStaff: bigint;
    totalRevenue: number;
    totalAppointments: bigint;
    totalCustomers: bigint;
}
export interface UserProfile {
    name: string;
}
export enum AppointmentStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}

export interface SalonWithId {
    id: bigint;
    name: string;
    address: string;
    phone: string;
    city: string;
    ownerPrincipal: any;
    isActive: boolean;
    trialStartDate: bigint;
    subscriptionActive: boolean;
}
export interface ServiceWithId {
    id: bigint;
    salonId: bigint;
    name: string;
    price: number;
    durationMinutes: bigint;
}
export interface AppointmentWithId {
    id: bigint;
    salonId: bigint;
    customerPrincipal: any;
    customerName: string;
    customerPhone: string;
    serviceName: string;
    queueNumber: bigint;
    status: string;
    createdAt: bigint;
    date: string;
}
export interface CustomerProfile {
    name: string;
    phone: string;
}
export interface backendInterface {
    registerSalon(name: string, address: string, phone: string, city: string): Promise<bigint>;
    updateMySalon(name: string, address: string, phone: string, city: string): Promise<void>;
    getMySalon(): Promise<SalonWithId | null>;
    addSalonService(salonId: bigint, name: string, price: number, durationMinutes: bigint): Promise<bigint>;
    deleteSalonService(salonId: bigint, serviceId: bigint): Promise<void>;
    getSalonServices(salonId: bigint): Promise<Array<ServiceWithId>>;
    getSalonAppointmentsForDate(salonId: bigint, date: string): Promise<Array<AppointmentWithId>>;
    getAllSalonAppointments(salonId: bigint): Promise<Array<AppointmentWithId>>;
    updateAppointmentStatus(appointmentId: bigint, newStatus: string): Promise<void>;
    getAllActiveSalons(): Promise<Array<SalonWithId>>;
    getSalonById(id: bigint): Promise<SalonWithId | null>;
    bookAppointment(salonId: bigint, customerName: string, customerPhone: string, serviceName: string, date: string): Promise<bigint>;
    getMyAppointments(): Promise<Array<AppointmentWithId>>;
    getQueueInfo(appointmentId: bigint): Promise<[bigint, bigint]>;
    saveCustomerProfile(name: string, phone: string): Promise<void>;
    getMyCustomerProfile(): Promise<CustomerProfile | null>;
    setPlatformSubscriptionPrice(price: number): Promise<void>;
    getPlatformSubscriptionPrice(): Promise<number>;
    adminGetAllSalons(): Promise<Array<SalonWithId>>;
    adminSetSalonSubscription(salonId: bigint, active: boolean): Promise<void>;
    adminSetSalonActive(salonId: bigint, active: boolean): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAppointment(appointment: Appointment): Promise<bigint>;
    createCustomer(customer: Customer): Promise<bigint>;
    createService(service: Service): Promise<bigint>;
    createStaff(staffMember: Staff): Promise<bigint>;
    deleteAppointment(id: bigint): Promise<void>;
    deleteCustomer(id: bigint): Promise<void>;
    deleteService(id: bigint): Promise<void>;
    deleteStaff(id: bigint): Promise<void>;
    getAllAppointments(): Promise<Array<Appointment>>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllServices(): Promise<Array<Service>>;
    getAllStaff(): Promise<Array<Staff>>;
    getAppointment(id: bigint): Promise<Appointment>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(id: bigint): Promise<Customer>;
    getDashboardStats(): Promise<DashboardStats>;
    getService(id: bigint): Promise<Service>;
    getStaff(id: bigint): Promise<Staff>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchAppointmentsByCustomerName(customerName: string): Promise<Array<Appointment>>;
    searchCustomersByName(name: string): Promise<Array<Customer>>;
    updateAppointment(id: bigint, appointment: Appointment): Promise<void>;
    updateCustomer(id: bigint, customer: Customer): Promise<void>;
    updateService(id: bigint, service: Service): Promise<void>;
    updateStaff(id: bigint, staffMember: Staff): Promise<void>;
}
import type { Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, Customer as _Customer, Service as _Service, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAppointment(arg0: Appointment): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(to_candid_Appointment_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(to_candid_Appointment_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCustomer(arg0: Customer): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(to_candid_Customer_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(to_candid_Customer_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createService(arg0: Service): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createService(to_candid_Service_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createService(to_candid_Service_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createStaff(arg0: Staff): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStaff(arg0);
            return result;
        }
    }
    async deleteAppointment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppointment(arg0);
            return result;
        }
    }
    async deleteCustomer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteService(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async deleteStaff(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStaff(arg0);
            return result;
        }
    }
    async getAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServices();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServices();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStaff(): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStaff();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStaff();
            return result;
        }
    }
    async getAppointment(arg0: bigint): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointment(arg0);
                return from_candid_Appointment_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointment(arg0);
            return from_candid_Appointment_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: bigint): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_Customer_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_Customer_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getService(arg0: bigint): Promise<Service> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_Service_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_Service_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaff(arg0: bigint): Promise<Staff> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaff(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchAppointmentsByCustomerName(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAppointmentsByCustomerName(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAppointmentsByCustomerName(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchCustomersByName(arg0: string): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCustomersByName(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCustomersByName(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAppointment(arg0: bigint, arg1: Appointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointment(arg0, to_candid_Appointment_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointment(arg0, to_candid_Appointment_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCustomer(arg0: bigint, arg1: Customer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, to_candid_Customer_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, to_candid_Customer_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateService(arg0: bigint, arg1: Service): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, to_candid_Service_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, to_candid_Service_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStaff(arg0: bigint, arg1: Staff): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaff(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaff(arg0, arg1);
            return result;
        }
    }

    async registerSalon(a: string, b: string, c: string, d: string): Promise<bigint> {
        return await this.actor.registerSalon(a, b, c, d);
    }
    async updateMySalon(a: string, b: string, c: string, d: string): Promise<void> {
        return await this.actor.updateMySalon(a, b, c, d);
    }
    async getMySalon(): Promise<SalonWithId | null> {
        const r = await this.actor.getMySalon();
        return r && r.length > 0 ? r[0] : null;
    }
    async addSalonService(salonId: bigint, name: string, price: number, durationMinutes: bigint): Promise<bigint> {
        return await this.actor.addSalonService(salonId, name, price, durationMinutes);
    }
    async deleteSalonService(salonId: bigint, serviceId: bigint): Promise<void> {
        return await this.actor.deleteSalonService(salonId, serviceId);
    }
    async getSalonServices(salonId: bigint): Promise<Array<ServiceWithId>> {
        return await this.actor.getSalonServices(salonId);
    }
    async getSalonAppointmentsForDate(salonId: bigint, date: string): Promise<Array<AppointmentWithId>> {
        return await this.actor.getSalonAppointmentsForDate(salonId, date);
    }
    async getAllSalonAppointments(salonId: bigint): Promise<Array<AppointmentWithId>> {
        return await this.actor.getAllSalonAppointments(salonId);
    }
    async updateAppointmentStatus(appointmentId: bigint, newStatus: string): Promise<void> {
        return await this.actor.updateAppointmentStatus(appointmentId, newStatus);
    }
    async getAllActiveSalons(): Promise<Array<SalonWithId>> {
        return await this.actor.getAllActiveSalons();
    }
    async getSalonById(id: bigint): Promise<SalonWithId | null> {
        const r = await this.actor.getSalonById(id);
        return r && r.length > 0 ? r[0] : null;
    }
    async bookAppointment(salonId: bigint, customerName: string, customerPhone: string, serviceName: string, date: string): Promise<bigint> {
        return await this.actor.bookAppointment(salonId, customerName, customerPhone, serviceName, date);
    }
    async getMyAppointments(): Promise<Array<AppointmentWithId>> {
        return await this.actor.getMyAppointments();
    }
    async getQueueInfo(appointmentId: bigint): Promise<[bigint, bigint]> {
        return await this.actor.getQueueInfo(appointmentId);
    }
    async saveCustomerProfile(name: string, phone: string): Promise<void> {
        return await this.actor.saveCustomerProfile(name, phone);
    }
    async getMyCustomerProfile(): Promise<CustomerProfile | null> {
        const r = await this.actor.getMyCustomerProfile();
        return r && r.length > 0 ? r[0] : null;
    }
    async setPlatformSubscriptionPrice(price: number): Promise<void> {
        return await this.actor.setPlatformSubscriptionPrice(price);
    }
    async getPlatformSubscriptionPrice(): Promise<number> {
        return await this.actor.getPlatformSubscriptionPrice();
    }
    async adminGetAllSalons(): Promise<Array<SalonWithId>> {
        return await this.actor.adminGetAllSalons();
    }
    async adminSetSalonSubscription(salonId: bigint, active: boolean): Promise<void> {
        return await this.actor.adminSetSalonSubscription(salonId, active);
    }
    async adminSetSalonActive(salonId: bigint, active: boolean): Promise<void> {
        return await this.actor.adminSetSalonActive(salonId, active);
    }
}
function from_candid_AppointmentStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Customer_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    status: _AppointmentStatus;
    serviceName: string;
    staffName: string;
    date: string;
    time: string;
    notes: [] | [string];
    price: number;
}): {
    customerName: string;
    status: AppointmentStatus;
    serviceName: string;
    staffName: string;
    date: string;
    time: string;
    notes?: string;
    price: number;
} {
    return {
        customerName: value.customerName,
        status: from_candid_AppointmentStatus_n14(_uploadFile, _downloadFile, value.status),
        serviceName: value.serviceName,
        staffName: value.staffName,
        date: value.date,
        time: value.time,
        notes: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.notes)),
        price: value.price
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    notes: [] | [string];
    phone: string;
}): {
    name: string;
    email: string;
    notes?: string;
    phone: string;
} {
    return {
        name: value.name,
        email: value.email,
        notes: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.notes)),
        phone: value.phone
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: bigint;
    name: string;
    description: [] | [string];
    price: number;
}): {
    duration: bigint;
    name: string;
    description?: string;
    price: number;
} {
    return {
        duration: value.duration,
        name: value.name,
        description: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.description)),
        price: value.price
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): AppointmentStatus {
    return "cancelled" in value ? AppointmentStatus.cancelled : "pending" in value ? AppointmentStatus.pending : "completed" in value ? AppointmentStatus.completed : "confirmed" in value ? AppointmentStatus.confirmed : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n21(_uploadFile, _downloadFile, x));
}
function to_candid_AppointmentStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): _AppointmentStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Appointment_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Appointment): _Appointment {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Customer_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Customer): _Customer {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Service_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Service): _Service {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: bigint;
    name: string;
    description?: string;
    price: number;
}): {
    duration: bigint;
    name: string;
    description: [] | [string];
    price: number;
} {
    return {
        duration: value.duration,
        name: value.name,
        description: value.description ? candid_some(value.description) : candid_none(),
        price: value.price
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    status: AppointmentStatus;
    serviceName: string;
    staffName: string;
    date: string;
    time: string;
    notes?: string;
    price: number;
}): {
    customerName: string;
    status: _AppointmentStatus;
    serviceName: string;
    staffName: string;
    date: string;
    time: string;
    notes: [] | [string];
    price: number;
} {
    return {
        customerName: value.customerName,
        status: to_candid_AppointmentStatus_n5(_uploadFile, _downloadFile, value.status),
        serviceName: value.serviceName,
        staffName: value.staffName,
        date: value.date,
        time: value.time,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        price: value.price
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    notes?: string;
    phone: string;
}): {
    name: string;
    email: string;
    notes: [] | [string];
    phone: string;
} {
    return {
        name: value.name,
        email: value.email,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        phone: value.phone
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == AppointmentStatus.cancelled ? {
        cancelled: null
    } : value == AppointmentStatus.pending ? {
        pending: null
    } : value == AppointmentStatus.completed ? {
        completed: null
    } : value == AppointmentStatus.confirmed ? {
        confirmed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
