/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PushSubscription {
    endpoint: string;
    auth: string;
    p256dh: string;
}
export interface SalonPhoto {
    id: bigint;
    url: string;
    ownerPhone: string;
    salonId: bigint;
    uploadedAt: bigint;
}
export interface SubscriptionHistory {
    id: bigint;
    finalPrice: number;
    originalPrice: number;
    endDate: bigint;
    approvedAt: bigint;
    ownerPhone: string;
    discountPercent: number;
    savings: number;
    planDays: bigint;
    planName: string;
    salonName: string;
    salonId: bigint;
    transactionId: string;
    startDate: bigint;
}
export interface CustomerProfile {
    name: string;
    phone: string;
}
export interface ServiceWithId {
    id: bigint;
    name: string;
    durationMinutes: bigint;
    price: number;
    salonId: bigint;
}
export interface OwnerRevenueSummary {
    monthlyEarnings: number;
    completedAppointments: bigint;
    totalEarnings: number;
    totalAppointments: bigint;
}
export interface RevenueStats {
    perSalon: Array<[bigint, string, number]>;
    totalRevenue: number;
    monthlyRevenue: number;
}
export interface DashboardStats {
    total: bigint;
    active: bigint;
    expired: bigint;
    pending: bigint;
}
export interface ServiceSession {
    startTime: bigint;
    durationMinutes: bigint;
    appointmentId: bigint;
}
export interface AppointmentWithId {
    id: bigint;
    customerName: string;
    status: string;
    serviceName: string;
    customerPhone: string;
    date: string;
    createdAt: bigint;
    queueNumber: bigint;
    servicePrice: number;
    salonId: bigint;
}
export interface SalonWithId {
    id: bigint;
    latitude?: number;
    trialDays: bigint;
    city: string;
    name: string;
    ownerPhone: string;
    pendingApproval: boolean;
    isActive: boolean;
    subscriptionActive: boolean;
    longitude?: number;
    address: string;
    phone: string;
    trialStartDate: bigint;
}
export interface PlanPricing {
    originalPrice: number;
    discountPercent: number;
    planDays: bigint;
    planName: string;
}
export interface QueueScheduleEntry {
    customerName: string;
    serviceName: string;
    estimatedStartTime: bigint;
    queueNumber: bigint;
    appointmentId: bigint;
}
export interface SubRequest {
    id: bigint;
    finalPrice: number;
    status: string;
    originalPrice: number;
    approvedAt: bigint;
    ownerPhone: string;
    discountPercent: number;
    savings: number;
    planDays: bigint;
    screenshotBase64: string;
    planName: string;
    salonName: string;
    requestTime: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addSalonServiceByPhone(ownerPhone: string, salonId: bigint, name: string, price: number, durationMinutes: bigint): Promise<bigint>;
    adminApproveSalon(email: string, passwordHash: string, salonId: bigint): Promise<void>;
    adminApproveSubRequest(email: string, passwordHash: string, requestId: bigint): Promise<boolean>;
    adminExpireOldSubRequests(email: string, passwordHash: string): Promise<bigint>;
    adminGetAllAppointmentsForBackup(email: string, passwordHash: string): Promise<Array<AppointmentWithId>>;
    adminGetAllCustomersForBackup(email: string, passwordHash: string): Promise<Array<CustomerProfile>>;
    adminGetAllPlanPricings(email: string, passwordHash: string): Promise<Array<PlanPricing>>;
    adminGetAllSalons(email: string, passwordHash: string): Promise<Array<SalonWithId>>;
    adminGetAllSalonsForBackup(email: string, passwordHash: string): Promise<Array<SalonWithId>>;
    adminGetAllServicesForBackup(email: string, passwordHash: string): Promise<Array<ServiceWithId>>;
    adminGetAllSubRequests(email: string, passwordHash: string): Promise<Array<SubRequest>>;
    adminGetDashboardStats(email: string, passwordHash: string): Promise<DashboardStats>;
    adminGetDefaultTrialDays(email: string, passwordHash: string): Promise<bigint>;
    adminGetNextIdsForBackup(email: string, passwordHash: string): Promise<[bigint, bigint, bigint]>;
    adminGetOwnerPhoneMapForBackup(email: string, passwordHash: string): Promise<Array<[string, bigint]>>;
    adminGetPendingSalons(email: string, passwordHash: string): Promise<Array<SalonWithId>>;
    adminGetPendingSubRequests(email: string, passwordHash: string): Promise<Array<SubRequest>>;
    adminGetRevenueStats(email: string, passwordHash: string): Promise<RevenueStats>;
    adminGetSubHistory(email: string, passwordHash: string): Promise<Array<SubscriptionHistory>>;
    adminGetSubRequestEarnings(email: string, passwordHash: string): Promise<[number, number, bigint]>;
    adminGetSubscriptionPrice(email: string, passwordHash: string): Promise<number>;
    adminLogin(email: string, passwordHash: string): Promise<boolean>;
    adminPasswordIsSet(): Promise<boolean>;
    adminProcessTrialExpirations(email: string, passwordHash: string): Promise<bigint>;
    adminRejectSalon(email: string, passwordHash: string, salonId: bigint): Promise<void>;
    adminRejectSubRequest(email: string, passwordHash: string, requestId: bigint): Promise<boolean>;
    adminResetOwnerPassword(email: string, passwordHash: string, ownerPhone: string, newPasswordHash: string): Promise<boolean>;
    adminRestoreAllData(email: string, passwordHash: string, salons: Array<SalonWithId>, svcs: Array<ServiceWithId>, appts: Array<AppointmentWithId>, custs: Array<CustomerProfile>, ownerPhoneMap: Array<[string, bigint]>, nSalonId: bigint, nServiceId: bigint, nAppointmentId: bigint): Promise<void>;
    adminSetDefaultTrialDays(email: string, passwordHash: string, days: bigint): Promise<void>;
    adminSetPassword(email: string, passwordHash: string): Promise<boolean>;
    adminSetPlanPricing(email: string, passwordHash: string, planName: string, originalPrice: number, discountPercent: number): Promise<void>;
    adminSetSalonActive(email: string, passwordHash: string, salonId: bigint, active: boolean): Promise<void>;
    adminSetSalonSubscription(email: string, passwordHash: string, salonId: bigint, active: boolean): Promise<void>;
    adminSetSalonTrialDays(email: string, passwordHash: string, salonId: bigint, days: bigint): Promise<void>;
    adminSetSubscriptionPrice(email: string, passwordHash: string, price: number): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookAppointmentByPhone(customerPhone: string, salonId: bigint, customerName: string, serviceName: string, date: string): Promise<bigint>;
    clearServiceSession(ownerPhone: string): Promise<void>;
    deleteSalonPhoto(ownerPhone: string, passwordHash: string, photoId: bigint): Promise<boolean>;
    deleteSalonServiceByPhone(ownerPhone: string, salonId: bigint, serviceId: bigint): Promise<void>;
    getAllActiveSalons(): Promise<Array<SalonWithId>>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentServiceSession(salonId: bigint): Promise<ServiceSession | null>;
    getMyAppointmentsByPhone(customerPhone: string): Promise<Array<AppointmentWithId>>;
    getMyCustomerProfileByPhone(phone: string): Promise<CustomerProfile | null>;
    getMySubHistory(ownerPhone: string): Promise<Array<SubscriptionHistory>>;
    getMySubRequests(ownerPhone: string): Promise<Array<SubRequest>>;
    getOwnerRevenueSummaryByPhone(ownerPhone: string): Promise<OwnerRevenueSummary>;
    getOwnerSalonByPhone(ownerPhone: string): Promise<SalonWithId | null>;
    getPendingNotifications(salonId: bigint, date: string): Promise<Array<bigint>>;
    getPlanPricings(): Promise<Array<PlanPricing>>;
    getPushSubscription(requestorPhone: string, customerPhone: string): Promise<PushSubscription | null>;
    getQueueInfo(appointmentId: bigint): Promise<[bigint, bigint]>;
    getQueueScheduleForSalon(salonId: bigint, date: string): Promise<Array<QueueScheduleEntry>>;
    getSalonAppointmentsForDateByPhone(ownerPhone: string, salonId: bigint, date: string): Promise<Array<AppointmentWithId>>;
    getSalonById(id: bigint): Promise<SalonWithId | null>;
    getSalonPhotos(salonId: bigint): Promise<Array<SalonPhoto>>;
    getSalonServices(salonId: bigint): Promise<Array<ServiceWithId>>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationSent(ownerPhone: string, appointmentId: bigint): Promise<void>;
    registerSalonByPhone(ownerPhone: string, name: string, address: string, phone: string, city: string): Promise<bigint>;
    salonOwnerLogin(ownerPhone: string, passwordHash: string): Promise<[string, SalonWithId | null]>;
    salonOwnerRegisterV2(ownerPhone: string, salonName: string, services: Array<string>, passwordHash: string): Promise<string>;
    salonOwnerSetPassword(ownerPhone: string, passwordHash: string): Promise<boolean>;
    saveCustomerProfileByPhone(phone: string, name: string): Promise<void>;
    savePushSubscription(customerPhone: string, endpoint: string, p256dh: string, auth: string): Promise<void>;
    startServiceSession(ownerPhone: string, appointmentId: bigint, durationMinutes: bigint): Promise<void>;
    submitSubscriptionRequest(ownerPhone: string, salonName: string, planName: string, planDays: bigint, originalPrice: number, discountPercent: number, finalPrice: number, savings: number, screenshotBase64: string): Promise<bigint>;
    updateAppointmentStatusByPhone(ownerPhone: string, appointmentId: bigint, newStatus: string): Promise<void>;
    updateOwnerSalonByPhone(ownerPhone: string, name: string, address: string, phone: string, city: string): Promise<void>;
    updateSalonLocation(ownerPhone: string, passwordHash: string, latitude: number, longitude: number): Promise<boolean>;
    uploadSalonPhoto(ownerPhone: string, passwordHash: string, url: string): Promise<bigint>;
}
import type { CustomerProfile as _CustomerProfile, PushSubscription as _PushSubscription, SalonWithId as _SalonWithId, ServiceSession as _ServiceSession, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addSalonServiceByPhone(arg0: string, arg1: bigint, arg2: string, arg3: number, arg4: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSalonServiceByPhone(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSalonServiceByPhone(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async adminApproveSalon(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveSalon(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveSalon(arg0, arg1, arg2);
            return result;
        }
    }
    async adminApproveSubRequest(arg0: string, arg1: string, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveSubRequest(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveSubRequest(arg0, arg1, arg2);
            return result;
        }
    }
    async adminExpireOldSubRequests(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminExpireOldSubRequests(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminExpireOldSubRequests(arg0, arg1);
            return result;
        }
    }
    async adminGetAllAppointmentsForBackup(arg0: string, arg1: string): Promise<Array<AppointmentWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllAppointmentsForBackup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllAppointmentsForBackup(arg0, arg1);
            return result;
        }
    }
    async adminGetAllCustomersForBackup(arg0: string, arg1: string): Promise<Array<CustomerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllCustomersForBackup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllCustomersForBackup(arg0, arg1);
            return result;
        }
    }
    async adminGetAllPlanPricings(arg0: string, arg1: string): Promise<Array<PlanPricing>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllPlanPricings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllPlanPricings(arg0, arg1);
            return result;
        }
    }
    async adminGetAllSalons(arg0: string, arg1: string): Promise<Array<SalonWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllSalons(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllSalons(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllSalonsForBackup(arg0: string, arg1: string): Promise<Array<SalonWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllSalonsForBackup(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllSalonsForBackup(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllServicesForBackup(arg0: string, arg1: string): Promise<Array<ServiceWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllServicesForBackup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllServicesForBackup(arg0, arg1);
            return result;
        }
    }
    async adminGetAllSubRequests(arg0: string, arg1: string): Promise<Array<SubRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllSubRequests(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllSubRequests(arg0, arg1);
            return result;
        }
    }
    async adminGetDashboardStats(arg0: string, arg1: string): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetDashboardStats(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetDashboardStats(arg0, arg1);
            return result;
        }
    }
    async adminGetDefaultTrialDays(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetDefaultTrialDays(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetDefaultTrialDays(arg0, arg1);
            return result;
        }
    }
    async adminGetNextIdsForBackup(arg0: string, arg1: string): Promise<[bigint, bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetNextIdsForBackup(arg0, arg1);
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetNextIdsForBackup(arg0, arg1);
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
    async adminGetOwnerPhoneMapForBackup(arg0: string, arg1: string): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetOwnerPhoneMapForBackup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetOwnerPhoneMapForBackup(arg0, arg1);
            return result;
        }
    }
    async adminGetPendingSalons(arg0: string, arg1: string): Promise<Array<SalonWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetPendingSalons(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetPendingSalons(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetPendingSubRequests(arg0: string, arg1: string): Promise<Array<SubRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetPendingSubRequests(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetPendingSubRequests(arg0, arg1);
            return result;
        }
    }
    async adminGetRevenueStats(arg0: string, arg1: string): Promise<RevenueStats> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetRevenueStats(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetRevenueStats(arg0, arg1);
            return result;
        }
    }
    async adminGetSubHistory(arg0: string, arg1: string): Promise<Array<SubscriptionHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetSubHistory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetSubHistory(arg0, arg1);
            return result;
        }
    }
    async adminGetSubRequestEarnings(arg0: string, arg1: string): Promise<[number, number, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetSubRequestEarnings(arg0, arg1);
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetSubRequestEarnings(arg0, arg1);
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
    async adminGetSubscriptionPrice(arg0: string, arg1: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetSubscriptionPrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetSubscriptionPrice(arg0, arg1);
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return result;
        }
    }
    async adminPasswordIsSet(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminPasswordIsSet();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminPasswordIsSet();
            return result;
        }
    }
    async adminProcessTrialExpirations(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.adminProcessTrialExpirations(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminProcessTrialExpirations(arg0, arg1);
            return result;
        }
    }
    async adminRejectSalon(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectSalon(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectSalon(arg0, arg1, arg2);
            return result;
        }
    }
    async adminRejectSubRequest(arg0: string, arg1: string, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectSubRequest(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectSubRequest(arg0, arg1, arg2);
            return result;
        }
    }
    async adminResetOwnerPassword(arg0: string, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminResetOwnerPassword(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminResetOwnerPassword(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminRestoreAllData(arg0: string, arg1: string, arg2: Array<SalonWithId>, arg3: Array<ServiceWithId>, arg4: Array<AppointmentWithId>, arg5: Array<CustomerProfile>, arg6: Array<[string, bigint]>, arg7: bigint, arg8: bigint, arg9: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRestoreAllData(arg0, arg1, to_candid_vec_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRestoreAllData(arg0, arg1, to_candid_vec_n5(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async adminSetDefaultTrialDays(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetDefaultTrialDays(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetDefaultTrialDays(arg0, arg1, arg2);
            return result;
        }
    }
    async adminSetPassword(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetPassword(arg0, arg1);
            return result;
        }
    }
    async adminSetPlanPricing(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetPlanPricing(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetPlanPricing(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async adminSetSalonActive(arg0: string, arg1: string, arg2: bigint, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetSalonActive(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetSalonActive(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminSetSalonSubscription(arg0: string, arg1: string, arg2: bigint, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetSalonSubscription(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetSalonSubscription(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminSetSalonTrialDays(arg0: string, arg1: string, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetSalonTrialDays(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetSalonTrialDays(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminSetSubscriptionPrice(arg0: string, arg1: string, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetSubscriptionPrice(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetSubscriptionPrice(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookAppointmentByPhone(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointmentByPhone(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointmentByPhone(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async clearServiceSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearServiceSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearServiceSession(arg0);
            return result;
        }
    }
    async deleteSalonPhoto(arg0: string, arg1: string, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSalonPhoto(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSalonPhoto(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteSalonServiceByPhone(arg0: string, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSalonServiceByPhone(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSalonServiceByPhone(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllActiveSalons(): Promise<Array<SalonWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveSalons();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveSalons();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentServiceSession(arg0: bigint): Promise<ServiceSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentServiceSession(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentServiceSession(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAppointmentsByPhone(arg0: string): Promise<Array<AppointmentWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAppointmentsByPhone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAppointmentsByPhone(arg0);
            return result;
        }
    }
    async getMyCustomerProfileByPhone(arg0: string): Promise<CustomerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCustomerProfileByPhone(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCustomerProfileByPhone(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubHistory(arg0: string): Promise<Array<SubscriptionHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubHistory(arg0);
            return result;
        }
    }
    async getMySubRequests(arg0: string): Promise<Array<SubRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubRequests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubRequests(arg0);
            return result;
        }
    }
    async getOwnerRevenueSummaryByPhone(arg0: string): Promise<OwnerRevenueSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnerRevenueSummaryByPhone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnerRevenueSummaryByPhone(arg0);
            return result;
        }
    }
    async getOwnerSalonByPhone(arg0: string): Promise<SalonWithId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnerSalonByPhone(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnerSalonByPhone(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingNotifications(arg0: bigint, arg1: string): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingNotifications(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingNotifications(arg0, arg1);
            return result;
        }
    }
    async getPlanPricings(): Promise<Array<PlanPricing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlanPricings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlanPricings();
            return result;
        }
    }
    async getPushSubscription(arg0: string, arg1: string): Promise<PushSubscription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPushSubscription(arg0, arg1);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPushSubscription(arg0, arg1);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQueueInfo(arg0: bigint): Promise<[bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getQueueInfo(arg0);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQueueInfo(arg0);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getQueueScheduleForSalon(arg0: bigint, arg1: string): Promise<Array<QueueScheduleEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQueueScheduleForSalon(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQueueScheduleForSalon(arg0, arg1);
            return result;
        }
    }
    async getSalonAppointmentsForDateByPhone(arg0: string, arg1: bigint, arg2: string): Promise<Array<AppointmentWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalonAppointmentsForDateByPhone(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalonAppointmentsForDateByPhone(arg0, arg1, arg2);
            return result;
        }
    }
    async getSalonById(arg0: bigint): Promise<SalonWithId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalonById(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalonById(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalonPhotos(arg0: bigint): Promise<Array<SalonPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalonPhotos(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalonPhotos(arg0);
            return result;
        }
    }
    async getSalonServices(arg0: bigint): Promise<Array<ServiceWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalonServices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalonServices(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationSent(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationSent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationSent(arg0, arg1);
            return result;
        }
    }
    async registerSalonByPhone(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerSalonByPhone(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerSalonByPhone(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async salonOwnerLogin(arg0: string, arg1: string): Promise<[string, SalonWithId | null]> {
        if (this.processError) {
            try {
                const result = await this.actor.salonOwnerLogin(arg0, arg1);
                return [
                    result[0],
                    from_candid_opt_n14(this._uploadFile, this._downloadFile, result[1])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.salonOwnerLogin(arg0, arg1);
            return [
                result[0],
                from_candid_opt_n14(this._uploadFile, this._downloadFile, result[1])
            ];
        }
    }
    async salonOwnerRegisterV2(arg0: string, arg1: string, arg2: Array<string>, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.salonOwnerRegisterV2(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.salonOwnerRegisterV2(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async salonOwnerSetPassword(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.salonOwnerSetPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.salonOwnerSetPassword(arg0, arg1);
            return result;
        }
    }
    async saveCustomerProfileByPhone(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCustomerProfileByPhone(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCustomerProfileByPhone(arg0, arg1);
            return result;
        }
    }
    async savePushSubscription(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePushSubscription(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePushSubscription(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async startServiceSession(arg0: string, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startServiceSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startServiceSession(arg0, arg1, arg2);
            return result;
        }
    }
    async submitSubscriptionRequest(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: number, arg5: number, arg6: number, arg7: number, arg8: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSubscriptionRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSubscriptionRequest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateAppointmentStatusByPhone(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointmentStatusByPhone(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointmentStatusByPhone(arg0, arg1, arg2);
            return result;
        }
    }
    async updateOwnerSalonByPhone(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOwnerSalonByPhone(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOwnerSalonByPhone(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateSalonLocation(arg0: string, arg1: string, arg2: number, arg3: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSalonLocation(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSalonLocation(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async uploadSalonPhoto(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadSalonPhoto(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadSalonPhoto(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_SalonWithId_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalonWithId): SalonWithId {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServiceSession]): ServiceSession | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerProfile]): CustomerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SalonWithId]): SalonWithId | null {
    return value.length === 0 ? null : from_candid_SalonWithId_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PushSubscription]): PushSubscription | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    latitude: [] | [number];
    trialDays: bigint;
    city: string;
    name: string;
    ownerPhone: string;
    pendingApproval: boolean;
    isActive: boolean;
    subscriptionActive: boolean;
    longitude: [] | [number];
    address: string;
    phone: string;
    trialStartDate: bigint;
}): {
    id: bigint;
    latitude?: number;
    trialDays: bigint;
    city: string;
    name: string;
    ownerPhone: string;
    pendingApproval: boolean;
    isActive: boolean;
    subscriptionActive: boolean;
    longitude?: number;
    address: string;
    phone: string;
    trialStartDate: bigint;
} {
    return {
        id: value.id,
        latitude: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.latitude)),
        trialDays: value.trialDays,
        city: value.city,
        name: value.name,
        ownerPhone: value.ownerPhone,
        pendingApproval: value.pendingApproval,
        isActive: value.isActive,
        subscriptionActive: value.subscriptionActive,
        longitude: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.longitude)),
        address: value.address,
        phone: value.phone,
        trialStartDate: value.trialStartDate
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SalonWithId>): Array<SalonWithId> {
    return value.map((x)=>from_candid_SalonWithId_n2(_uploadFile, _downloadFile, x));
}
function to_candid_SalonWithId_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SalonWithId): _SalonWithId {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    latitude?: number;
    trialDays: bigint;
    city: string;
    name: string;
    ownerPhone: string;
    pendingApproval: boolean;
    isActive: boolean;
    subscriptionActive: boolean;
    longitude?: number;
    address: string;
    phone: string;
    trialStartDate: bigint;
}): {
    id: bigint;
    latitude: [] | [number];
    trialDays: bigint;
    city: string;
    name: string;
    ownerPhone: string;
    pendingApproval: boolean;
    isActive: boolean;
    subscriptionActive: boolean;
    longitude: [] | [number];
    address: string;
    phone: string;
    trialStartDate: bigint;
} {
    return {
        id: value.id,
        latitude: value.latitude ? candid_some(value.latitude) : candid_none(),
        trialDays: value.trialDays,
        city: value.city,
        name: value.name,
        ownerPhone: value.ownerPhone,
        pendingApproval: value.pendingApproval,
        isActive: value.isActive,
        subscriptionActive: value.subscriptionActive,
        longitude: value.longitude ? candid_some(value.longitude) : candid_none(),
        address: value.address,
        phone: value.phone,
        trialStartDate: value.trialStartDate
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SalonWithId>): Array<_SalonWithId> {
    return value.map((x)=>to_candid_SalonWithId_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
